name: Test valid_dirs Condition

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test-condition:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Test Environment
      id: changed-dirs
      run: |
        # Simulate different scenarios for valid_dirs
        echo "## Simulating an empty valid_dirs"
        echo "valid_dirs=test/dir and/one/more" >> $GITHUB_ENV

    - name: Check for Valid Directories
      id: check-dirs
      run: |
        # Trim spaces from the valid_dirs variable
        TRIMMED_VALID_DIRS=$(echo "${{ env.valid_dirs }}" | xargs)
        if [ -z "$TRIMMED_VALID_DIRS" ]; then
          echo "No valid directories found. Skipping workflow."
          echo "should-run=false" >> $GITHUB_OUTPUT
        else
          echo "Valid directories found: $TRIMMED_VALID_DIRS"
          echo "should-run=true" >> $GITHUB_OUTPUT
        fi

    - name: Test Non-Empty valid_dirs Condition
      if: steps.check-dirs.outputs.should-run == 'true'
      run: |
        echo "should-run is TRUE"
        echo "This step should run if valid_dirs is not empty."
        echo "valid_dirs:${{ env.valid_dirs }}."
    - name: Test if Empty valid_dirs Condition
      if: steps.check-dirs.outputs.should-run != 'true'
      run: |
        echo "should-run NOT TRUE"
        echo "This step should NOT run if valid_dirs is not empty."
        echo "valid_dirs:${{ env.valid_dirs }}."
