name: Test valid_dirs Condition

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test-condition:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Test Environment
      id: changed-dirs
      run: |
        # Simulate different scenarios for valid_dirs
        echo "## Simulating an empty valid_dirs"
        echo "valid_dirs=" >> $GITHUB_ENV

    - name: Test Empty valid_dirs Condition
      if: env.valid_dirs == ''
      run: |
        echo "Condition passed: valid_dirs is empty."
        echo "Test successful: Workflow correctly identifies an empty valid_dirs."

    - name: Test Non-Empty valid_dirs Condition
      if: env.valid_dirs != ''
      run: |
        echo "Condition failed: valid_dirs is not empty."
        echo "This step should not run if valid_dirs is empty."
